baseurl = "https://eclipse.org/opensmartclide"
# baseurl = "" # Fixes staging build
# relativeurls = true # Fixes staging build (bad css)
DefaultContentLanguage = "en"
title = "" 
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
GoogleAnalytics = "UA-164550450-2"
disableKinds = ["taxonomyTerm"]
themesDir = "node_modules/"
twitter_url = "https://twitter.com/smartclide"

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "The SmartCLIDE project will enable organizations on the path to digitalization to accelerate the creation and adoption of Cloud solutions. The innovative smart cloud-native development environment will support creators of cloud services in the discovery, creation, composition, testing, and deployment of full-stack data-centered services and applications in the cloud."
  subtitle = ""
  seo_title_suffix = " | OpenSmartCLIDE Project"
  keywords = []
  logo = "images/panorama-logo.svg"
  styles = "css/styles.css"
  favicon = "images/panorama-favicon.ico"
# share_img = ""
#gcse = "011805775785170369411:p3ec0igo0qq"
  gcse=""
# subtheme = ""
  header_wrapper_class = "header-default-bg-img"
  js = "js/solstice.js"
# call_for_action_text = ""
# call_for_action_url = ""
# call_for_action_icon = ""
  title = "Our lates news"


#[Params.recent_posts]
#    enable = true
#    title = "Our latest news"
#    subtitle = ""


[taxonomies]
  category = "categories"
  tag = "tags"
  participation_level = "participation_levels"

[Author]
  name = "Panorama Project"
  website = "https://panorama-research.org/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    name = "News"
    url = "/news/"
    weight = 2

[[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 3

[[menu.main]]
  name = "PMI"
  url = "https://projects.eclipse.org/projects/ecd.opensmartclide"
  weight = 4


